# SRC: https://github.com/sprintcube/docker-compose-lamp/blob/1d8e745cfcbb8de1755f645f1fc45a0171540c3f/docker-compose.yml
version: "3"

services:
  webserver:
    build: 
      context: ./dockerfile/php
    container_name: '${COMPOSE_PROJECT_NAME}-webserver'
    restart: 'on-failure'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - database
    volumes: 
      - ${DOCUMENT_ROOT-./src/www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${LOG_DIR-./log/apache2}:/var/log/apache2
      - ${PHP_INCLUDE-./src/include}:/var/lib/php
    environment:
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  database:
    image: mariadb:10.4
    container_name: '${COMPOSE_PROJECT_NAME}-database'
    restart: 'on-failure'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_INITDB_DIR-./config/db/initdb}:/docker-entrypoint-initdb.d/
      - ${MYSQL_DATA_DIR-./data/db}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./log/db}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
    volumes: 
      - /sessions
        #- ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
